namespace RelayCove.Core;

public sealed record ChannelDetails(
    long ChannelId,
    string Name,
    string? Description,
    bool IsArchived,
    bool IsPrivate,
    bool IsWebPublic,
    int? SubscriberCount,
    int? WeeklyTraffic,
    long? FolderId,
    long? CreatorId,
    DateTimeOffset? DateCreated,
    ChannelGroupSetting? CanAdministerChannelGroup,
    ChannelGroupSetting? CanAddSubscribersGroup = null,
    ChannelGroupSetting? CanSendMessageGroup = null,
    ChannelGroupSetting? CanSubscribeGroup = null,
    ChannelGroupSetting? CanCreateTopicGroup = null,
    bool HistoryPublicToSubscribers = false,
    bool IsDefaultStream = false,
    ChannelTopicsPolicy? TopicsPolicy = null,
    int? MessageRetentionDays = null,
    ChannelGroupSetting? CanRemoveSubscribersGroup = null,
    ChannelGroupSetting? CanMoveMessagesWithinChannelGroup = null,
    ChannelGroupSetting? CanMoveMessagesOutOfChannelGroup = null,
    ChannelGroupSetting? CanResolveTopicsGroup = null,
    ChannelGroupSetting? CanDeleteAnyMessageGroup = null,
    ChannelGroupSetting? CanDeleteOwnMessageGroup = null);
