// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RelayCove.Server.Data;

#nullable disable

namespace RelayCove.Server.Data.Migrations
{
    [DbContext(typeof(RelayCoveDbContext))]
    [Migration("20260803055556_AddConversationStorage")]
    partial class AddConversationStorage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("RelayCove.Server.Data.Entities.Conversation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarAttachmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DirectParticipantKey")
                        .HasMaxLength(73)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DirectParticipantKey")
                        .IsUnique();

                    b.HasIndex("Type");

                    b.ToTable("Conversations", null, t =>
                        {
                            t.HasCheckConstraint("CK_Conversations_AvatarAttachmentId_Format", "\"AvatarAttachmentId\" IS NULL OR (\"AvatarAttachmentId\" GLOB '[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]' AND \"AvatarAttachmentId\" <> '00000000-0000-0000-0000-000000000000')");

                            t.HasCheckConstraint("CK_Conversations_CreatedAt_Format", "\"CreatedAt\" GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'");

                            t.HasCheckConstraint("CK_Conversations_CreatedByUserId_Format", "\"CreatedByUserId\" GLOB '[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]' AND \"CreatedByUserId\" <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("CK_Conversations_DirectParticipantKey_ByType", "(\"Type\" IN (1, 2) AND \"DirectParticipantKey\" IS NULL) OR (\"Type\" = 3 AND \"DirectParticipantKey\" IS NOT NULL AND length(\"DirectParticipantKey\") = 73 AND substr(\"DirectParticipantKey\", 37, 1) = ':' AND substr(\"DirectParticipantKey\", 1, 36) GLOB '[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]' AND substr(\"DirectParticipantKey\", 38, 36) GLOB '[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]' AND substr(\"DirectParticipantKey\", 1, 36) <> '00000000-0000-0000-0000-000000000000' AND substr(\"DirectParticipantKey\", 38, 36) <> '00000000-0000-0000-0000-000000000000' AND substr(\"DirectParticipantKey\", 1, 36) < substr(\"DirectParticipantKey\", 38, 36) AND \"CreatedByUserId\" IN (substr(\"DirectParticipantKey\", 1, 36), substr(\"DirectParticipantKey\", 38, 36)))");

                            t.HasCheckConstraint("CK_Conversations_Id_Format", "\"Id\" GLOB '[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]' AND \"Id\" <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("CK_Conversations_IsDeleted_Boolean", "\"IsDeleted\" IN (0, 1)");

                            t.HasCheckConstraint("CK_Conversations_Name_ByType", "(\"Type\" IN (1, 2) AND length(\"Name\") BETWEEN 1 AND 100 AND length(trim(\"Name\")) > 0) OR (\"Type\" = 3 AND \"Name\" = '')");

                            t.HasCheckConstraint("CK_Conversations_Type_Value", "\"Type\" IN (1, 2, 3)");

                            t.HasCheckConstraint("CK_Conversations_Update_Order", "\"UpdatedAt\" >= \"CreatedAt\"");

                            t.HasCheckConstraint("CK_Conversations_UpdatedAt_Format", "\"UpdatedAt\" GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'");
                        });
                });

            modelBuilder.Entity("RelayCove.Server.Data.Entities.ConversationMember", b =>
                {
                    b.Property<string>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsMuted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("JoinedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("LastReadMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("ConversationId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ConversationMembers", null, t =>
                        {
                            t.HasCheckConstraint("CK_ConversationMembers_ConversationId_Format", "\"ConversationId\" GLOB '[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]' AND \"ConversationId\" <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("CK_ConversationMembers_IsMuted_Boolean", "\"IsMuted\" IN (0, 1)");

                            t.HasCheckConstraint("CK_ConversationMembers_JoinedAt_Format", "\"JoinedAt\" GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'");

                            t.HasCheckConstraint("CK_ConversationMembers_LastReadMessageId_NonNegative", "\"LastReadMessageId\" >= 0");

                            t.HasCheckConstraint("CK_ConversationMembers_Role_Value", "\"Role\" IN (1, 2)");

                            t.HasCheckConstraint("CK_ConversationMembers_UserId_Format", "\"UserId\" GLOB '[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]' AND \"UserId\" <> '00000000-0000-0000-0000-000000000000'");
                        });
                });

            modelBuilder.Entity("RelayCove.Server.Data.Entities.RefreshToken", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpiresAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(43)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", null, t =>
                        {
                            t.HasCheckConstraint("CK_RefreshTokens_CreatedAt_Format", "\"CreatedAt\" GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'");

                            t.HasCheckConstraint("CK_RefreshTokens_DeviceName_Length", "length(\"DeviceName\") BETWEEN 1 AND 128");

                            t.HasCheckConstraint("CK_RefreshTokens_ExpiresAt_Format", "\"ExpiresAt\" GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'");

                            t.HasCheckConstraint("CK_RefreshTokens_Expiry_Order", "\"ExpiresAt\" > \"CreatedAt\"");

                            t.HasCheckConstraint("CK_RefreshTokens_Id_Format", "\"Id\" GLOB '[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]' AND \"Id\" <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("CK_RefreshTokens_RevokedAt_Format", "\"RevokedAt\" IS NULL OR (\"RevokedAt\" GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z')");

                            t.HasCheckConstraint("CK_RefreshTokens_TokenHash_Format", "length(\"TokenHash\") = 43 AND \"TokenHash\" NOT GLOB '*[^A-Za-z0-9_-]*'");

                            t.HasCheckConstraint("CK_RefreshTokens_UserId_Format", "\"UserId\" GLOB '[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]' AND \"UserId\" <> '00000000-0000-0000-0000-000000000000'");
                        });
                });

            modelBuilder.Entity("RelayCove.Server.Data.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarAttachmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastOnlineAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("CK_Users_CreatedAt_Format", "\"CreatedAt\" GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'");

                            t.HasCheckConstraint("CK_Users_DisplayName_Length", "length(\"DisplayName\") BETWEEN 1 AND 100");

                            t.HasCheckConstraint("CK_Users_Id_Format", "\"Id\" GLOB '[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]' AND \"Id\" <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("CK_Users_IsAdmin_Boolean", "\"IsAdmin\" IN (0, 1)");

                            t.HasCheckConstraint("CK_Users_IsDisabled_Boolean", "\"IsDisabled\" IN (0, 1)");

                            t.HasCheckConstraint("CK_Users_LastLoginAt_Format", "\"LastLoginAt\" IS NULL OR (\"LastLoginAt\" GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z')");

                            t.HasCheckConstraint("CK_Users_LastOnlineAt_Format", "\"LastOnlineAt\" IS NULL OR (\"LastOnlineAt\" GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z')");

                            t.HasCheckConstraint("CK_Users_NameNormalization", "upper(\"UserName\") = \"NormalizedUserName\"");

                            t.HasCheckConstraint("CK_Users_NormalizedUserName_Format", "length(\"NormalizedUserName\") BETWEEN 3 AND 64 AND \"NormalizedUserName\" NOT GLOB '*[^A-Z0-9._-]*' AND \"NormalizedUserName\" GLOB '*[A-Z0-9]*' AND upper(\"NormalizedUserName\") = \"NormalizedUserName\"");

                            t.HasCheckConstraint("CK_Users_PasswordHash_NotEmpty", "length(\"PasswordHash\") > 0");

                            t.HasCheckConstraint("CK_Users_UpdatedAt_Format", "\"UpdatedAt\" GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'");

                            t.HasCheckConstraint("CK_Users_UserName_Format", "length(\"UserName\") BETWEEN 3 AND 64 AND \"UserName\" NOT GLOB '*[^A-Za-z0-9._-]*' AND \"UserName\" GLOB '*[A-Za-z0-9]*'");
                        });
                });

            modelBuilder.Entity("RelayCove.Server.Data.Entities.Conversation", b =>
                {
                    b.HasOne("RelayCove.Server.Data.Entities.User", "CreatedByUser")
                        .WithMany("CreatedConversations")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("RelayCove.Server.Data.Entities.ConversationMember", b =>
                {
                    b.HasOne("RelayCove.Server.Data.Entities.Conversation", "Conversation")
                        .WithMany("Members")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RelayCove.Server.Data.Entities.User", "User")
                        .WithMany("ConversationMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RelayCove.Server.Data.Entities.RefreshToken", b =>
                {
                    b.HasOne("RelayCove.Server.Data.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RelayCove.Server.Data.Entities.Conversation", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("RelayCove.Server.Data.Entities.User", b =>
                {
                    b.Navigation("ConversationMemberships");

                    b.Navigation("CreatedConversations");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
