// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RelayCove.Server.Data;

#nullable disable

namespace RelayCove.Server.Data.Migrations
{
    [DbContext(typeof(RelayCoveDbContext))]
    [Migration("20260803040433_InitialAuthenticationStorage")]
    partial class InitialAuthenticationStorage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("RelayCove.Server.Data.Entities.RefreshToken", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpiresAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(43)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", null, t =>
                        {
                            t.HasCheckConstraint("CK_RefreshTokens_CreatedAt_Format", "length(\"CreatedAt\") = 24 AND substr(\"CreatedAt\", 5, 1) = '-' AND substr(\"CreatedAt\", 8, 1) = '-' AND substr(\"CreatedAt\", 11, 1) = 'T' AND substr(\"CreatedAt\", 14, 1) = ':' AND substr(\"CreatedAt\", 17, 1) = ':' AND substr(\"CreatedAt\", 20, 1) = '.' AND substr(\"CreatedAt\", 24, 1) = 'Z'");

                            t.HasCheckConstraint("CK_RefreshTokens_DeviceName_Length", "length(\"DeviceName\") BETWEEN 1 AND 128");

                            t.HasCheckConstraint("CK_RefreshTokens_ExpiresAt_Format", "length(\"ExpiresAt\") = 24 AND substr(\"ExpiresAt\", 5, 1) = '-' AND substr(\"ExpiresAt\", 8, 1) = '-' AND substr(\"ExpiresAt\", 11, 1) = 'T' AND substr(\"ExpiresAt\", 14, 1) = ':' AND substr(\"ExpiresAt\", 17, 1) = ':' AND substr(\"ExpiresAt\", 20, 1) = '.' AND substr(\"ExpiresAt\", 24, 1) = 'Z'");

                            t.HasCheckConstraint("CK_RefreshTokens_Expiry_Order", "\"ExpiresAt\" > \"CreatedAt\"");

                            t.HasCheckConstraint("CK_RefreshTokens_Id_Format", "length(\"Id\") = 36 AND lower(\"Id\") = \"Id\" AND substr(\"Id\", 9, 1) = '-' AND substr(\"Id\", 14, 1) = '-' AND substr(\"Id\", 19, 1) = '-' AND substr(\"Id\", 24, 1) = '-'");

                            t.HasCheckConstraint("CK_RefreshTokens_RevokedAt_Format", "\"RevokedAt\" IS NULL OR (length(\"RevokedAt\") = 24 AND substr(\"RevokedAt\", 5, 1) = '-' AND substr(\"RevokedAt\", 8, 1) = '-' AND substr(\"RevokedAt\", 11, 1) = 'T' AND substr(\"RevokedAt\", 14, 1) = ':' AND substr(\"RevokedAt\", 17, 1) = ':' AND substr(\"RevokedAt\", 20, 1) = '.' AND substr(\"RevokedAt\", 24, 1) = 'Z')");

                            t.HasCheckConstraint("CK_RefreshTokens_TokenHash_Format", "length(\"TokenHash\") = 43 AND \"TokenHash\" NOT GLOB '*[^A-Za-z0-9_-]*'");

                            t.HasCheckConstraint("CK_RefreshTokens_UserId_Format", "length(\"UserId\") = 36 AND lower(\"UserId\") = \"UserId\" AND substr(\"UserId\", 9, 1) = '-' AND substr(\"UserId\", 14, 1) = '-' AND substr(\"UserId\", 19, 1) = '-' AND substr(\"UserId\", 24, 1) = '-'");
                        });
                });

            modelBuilder.Entity("RelayCove.Server.Data.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarAttachmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastOnlineAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("CK_Users_CreatedAt_Format", "length(\"CreatedAt\") = 24 AND substr(\"CreatedAt\", 5, 1) = '-' AND substr(\"CreatedAt\", 8, 1) = '-' AND substr(\"CreatedAt\", 11, 1) = 'T' AND substr(\"CreatedAt\", 14, 1) = ':' AND substr(\"CreatedAt\", 17, 1) = ':' AND substr(\"CreatedAt\", 20, 1) = '.' AND substr(\"CreatedAt\", 24, 1) = 'Z'");

                            t.HasCheckConstraint("CK_Users_DisplayName_Length", "length(\"DisplayName\") BETWEEN 1 AND 100");

                            t.HasCheckConstraint("CK_Users_Id_Format", "length(\"Id\") = 36 AND lower(\"Id\") = \"Id\" AND substr(\"Id\", 9, 1) = '-' AND substr(\"Id\", 14, 1) = '-' AND substr(\"Id\", 19, 1) = '-' AND substr(\"Id\", 24, 1) = '-'");

                            t.HasCheckConstraint("CK_Users_IsAdmin_Boolean", "\"IsAdmin\" IN (0, 1)");

                            t.HasCheckConstraint("CK_Users_IsDisabled_Boolean", "\"IsDisabled\" IN (0, 1)");

                            t.HasCheckConstraint("CK_Users_LastLoginAt_Format", "\"LastLoginAt\" IS NULL OR (length(\"LastLoginAt\") = 24 AND substr(\"LastLoginAt\", 5, 1) = '-' AND substr(\"LastLoginAt\", 8, 1) = '-' AND substr(\"LastLoginAt\", 11, 1) = 'T' AND substr(\"LastLoginAt\", 14, 1) = ':' AND substr(\"LastLoginAt\", 17, 1) = ':' AND substr(\"LastLoginAt\", 20, 1) = '.' AND substr(\"LastLoginAt\", 24, 1) = 'Z')");

                            t.HasCheckConstraint("CK_Users_LastOnlineAt_Format", "\"LastOnlineAt\" IS NULL OR (length(\"LastOnlineAt\") = 24 AND substr(\"LastOnlineAt\", 5, 1) = '-' AND substr(\"LastOnlineAt\", 8, 1) = '-' AND substr(\"LastOnlineAt\", 11, 1) = 'T' AND substr(\"LastOnlineAt\", 14, 1) = ':' AND substr(\"LastOnlineAt\", 17, 1) = ':' AND substr(\"LastOnlineAt\", 20, 1) = '.' AND substr(\"LastOnlineAt\", 24, 1) = 'Z')");

                            t.HasCheckConstraint("CK_Users_NormalizedUserName_Format", "length(\"NormalizedUserName\") BETWEEN 3 AND 64 AND \"NormalizedUserName\" NOT GLOB '*[^A-Z0-9._-]*' AND upper(\"NormalizedUserName\") = \"NormalizedUserName\"");

                            t.HasCheckConstraint("CK_Users_PasswordHash_NotEmpty", "length(\"PasswordHash\") > 0");

                            t.HasCheckConstraint("CK_Users_UpdatedAt_Format", "length(\"UpdatedAt\") = 24 AND substr(\"UpdatedAt\", 5, 1) = '-' AND substr(\"UpdatedAt\", 8, 1) = '-' AND substr(\"UpdatedAt\", 11, 1) = 'T' AND substr(\"UpdatedAt\", 14, 1) = ':' AND substr(\"UpdatedAt\", 17, 1) = ':' AND substr(\"UpdatedAt\", 20, 1) = '.' AND substr(\"UpdatedAt\", 24, 1) = 'Z'");

                            t.HasCheckConstraint("CK_Users_UserName_Format", "length(\"UserName\") BETWEEN 3 AND 64 AND \"UserName\" NOT GLOB '*[^A-Za-z0-9._-]*'");
                        });
                });

            modelBuilder.Entity("RelayCove.Server.Data.Entities.RefreshToken", b =>
                {
                    b.HasOne("RelayCove.Server.Data.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RelayCove.Server.Data.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
